<project name ="app1" default = "compile">

<property name="lib.dir" value="lib"/>
<property name="classes.dir" value="classes"/>


<path id="compile.classpath">
		<fileset dir="${lib.dir}">
			<include name="**/*.jar"/>
		</fileset>
</path>


<path id="run.classpath">
	<pathelement location="${classes.dir}" /> 
		<fileset dir="${lib.dir}">
			<include name="**/*.jar"/>
		</fileset>
</path>

<target name="print-classpath">
	<pathconvert property="classpathInName" refid="run.classpath" />
	<echo>Classpath is ${classpathInName}</echo>
</target>


<target name="print-compile-classpath">
	<pathconvert property="classpathInName" refid="compile.classpath" />
	<echo>Classpath is ${classpathInName}</echo>
</target>



<target name = "compile">
	<javac srcdir="src" destdir="classes"  includeantruntime="false">
		<classpath refid="compile.classpath"/>
	</javac>
</target>

<target name="run" depends="compile">
	<java classname = "j1">
		<classpath refid="run.classpath"/>
	</java>
</target>




</project>