<ivy-module version="2.0">
    <info organisation="org.apache" module="hello-ivy"/>
    <dependencies>
<!-- Source: https://mvnrepository.com/artifact/org.apache.lucene/lucene-core -->
<dependency org="org.apache.lucene" name="lucene-core" rev="8.11.4"/>
<!-- Source: https://mvnrepository.com/artifact/org.apache.lucene/lucene-queryparser -->
<dependency org="org.apache.lucene" name="lucene-queryparser" rev="8.11.4"/>

<!-- Source: https://mvnrepository.com/artifact/org.apache.lucene/lucene-analyzers-common -->
<dependency org="org.apache.lucene" name="lucene-analyzers-common" rev="8.11.4"/>  

    </dependencies>
</ivy-module>
